###############################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

FROM openjdk:8
MAINTAINER "Apache Beam <dev@beam.apache.org>"

ADD target/slf4j-api.jar /opt/apache/beam/jars/
ADD target/slf4j-jdk14.jar /opt/apache/beam/jars/
ADD target/beam-sdks-java-harness.jar /opt/apache/beam/jars/


ADD target/akka-actor_2.11-2.4.20.jar /opt/apache/beam/jars/
ADD target/akka-protobuf_2.11-2.4.20.jar /opt/apache/beam/jars/
ADD target/akka-slf4j_2.11-2.4.20.jar /opt/apache/beam/jars/
ADD target/akka-stream_2.11-2.4.20.jar /opt/apache/beam/jars/
ADD target/avro-1.8.2.jar /opt/apache/beam/jars/
ADD target/chill-java-0.7.4.jar /opt/apache/beam/jars/
ADD target/chill_2.11-0.7.4.jar /opt/apache/beam/jars/
ADD target/commons-cli-1.3.1.jar /opt/apache/beam/jars/
ADD target/commons-collections-3.2.2.jar /opt/apache/beam/jars/
ADD target/commons-compress-1.14.jar /opt/apache/beam/jars/
ADD target/commons-io-2.5.jar /opt/apache/beam/jars/
ADD target/commons-lang3-3.6.jar /opt/apache/beam/jars/
ADD target/commons-math3-3.5.jar /opt/apache/beam/jars/
ADD target/config-1.3.0.jar /opt/apache/beam/jars/
ADD target/core-2.4.0-SNAPSHOT-shaded-tests.jar /opt/apache/beam/jars/
ADD target/core-2.4.0-SNAPSHOT-shaded.jar /opt/apache/beam/jars/
ADD target/core-construction-java-2.4.0-SNAPSHOT-shaded.jar /opt/apache/beam/jars/
ADD target/core-java-2.4.0-SNAPSHOT-shaded.jar /opt/apache/beam/jars/
ADD target/error_prone_annotations-2.0.15.jar /opt/apache/beam/jars/
ADD target/flink-2.4.0-SNAPSHOT-shaded.jar /opt/apache/beam/jars/
ADD target/flink-annotations-1.4.0.jar /opt/apache/beam/jars/
ADD target/flink-clients_2.11-1.4.0.jar /opt/apache/beam/jars/
ADD target/flink-core-1.4.0.jar /opt/apache/beam/jars/
ADD target/flink-hadoop-fs-1.4.0.jar /opt/apache/beam/jars/
ADD target/flink-java-1.4.0.jar /opt/apache/beam/jars/
ADD target/flink-metrics-core-1.4.0.jar /opt/apache/beam/jars/
ADD target/flink-optimizer_2.11-1.4.0.jar /opt/apache/beam/jars/
ADD target/flink-queryable-state-client-java_2.11-1.4.0.jar /opt/apache/beam/jars/
ADD target/flink-runtime_2.11-1.4.0.jar /opt/apache/beam/jars/
ADD target/flink-shaded-asm-5.0.4-2.0.jar /opt/apache/beam/jars/
ADD target/flink-shaded-guava-18.0-2.0.jar /opt/apache/beam/jars/
ADD target/flink-shaded-jackson-2.7.9-2.0.jar /opt/apache/beam/jars/
ADD target/flink-shaded-netty-4.0.27.Final-2.0.jar /opt/apache/beam/jars/
ADD target/flink-streaming-java_2.11-1.4.0.jar /opt/apache/beam/jars/
ADD target/fn-execution-2.4.0-SNAPSHOT-shaded.jar /opt/apache/beam/jars/
ADD target/force-shading-1.4.0.jar /opt/apache/beam/jars/
ADD target/grizzled-slf4j_2.11-1.0.2.jar /opt/apache/beam/jars/
ADD target/grpc-context-1.2.0.jar /opt/apache/beam/jars/
ADD target/grpc-core-1.2.0.jar /opt/apache/beam/jars/
ADD target/grpc-netty-1.2.0.jar /opt/apache/beam/jars/
ADD target/grpc-protobuf-1.2.0.jar /opt/apache/beam/jars/
ADD target/grpc-protobuf-lite-1.2.0.jar /opt/apache/beam/jars/
ADD target/grpc-stub-1.2.0.jar /opt/apache/beam/jars/
ADD target/gson-2.7.jar /opt/apache/beam/jars/
ADD target/guava-20.0.jar /opt/apache/beam/jars/
ADD target/guava-testlib-20.0.jar /opt/apache/beam/jars/
ADD target/hamcrest-core-1.3.jar /opt/apache/beam/jars/
ADD target/hamcrest-library-1.3.jar /opt/apache/beam/jars/
ADD target/harness-2.4.0-SNAPSHOT-all.jar /opt/apache/beam/jars/
ADD target/instrumentation-api-0.3.0.jar /opt/apache/beam/jars/
ADD target/jackson-annotations-2.8.9.jar /opt/apache/beam/jars/
ADD target/jackson-core-2.8.9.jar /opt/apache/beam/jars/
ADD target/jackson-core-asl-1.9.13.jar /opt/apache/beam/jars/
ADD target/jackson-databind-2.8.9.jar /opt/apache/beam/jars/
ADD target/jackson-dataformat-yaml-2.8.9.jar /opt/apache/beam/jars/
ADD target/jackson-mapper-asl-1.9.13.jar /opt/apache/beam/jars/
ADD target/java-fn-execution-2.4.0-SNAPSHOT-shaded.jar /opt/apache/beam/jars/
ADD target/javassist-3.18.2-GA.jar /opt/apache/beam/jars/
ADD target/job-management-2.4.0-SNAPSHOT-shaded.jar /opt/apache/beam/jars/
ADD target/joda-time-2.4.jar /opt/apache/beam/jars/
ADD target/jsr305-3.0.1.jar /opt/apache/beam/jars/
ADD target/junit-4.12.jar /opt/apache/beam/jars/
ADD target/kryo-2.24.0.jar /opt/apache/beam/jars/
ADD target/minlog-1.2.jar /opt/apache/beam/jars/
ADD target/mockito-core-1.9.5.jar /opt/apache/beam/jars/
ADD target/netty-buffer-4.1.8.Final.jar /opt/apache/beam/jars/
ADD target/netty-codec-4.1.8.Final.jar /opt/apache/beam/jars/
ADD target/netty-codec-http-4.1.8.Final.jar /opt/apache/beam/jars/
ADD target/netty-codec-http2-4.1.8.Final.jar /opt/apache/beam/jars/
ADD target/netty-codec-socks-4.1.8.Final.jar /opt/apache/beam/jars/
ADD target/netty-common-4.1.8.Final.jar /opt/apache/beam/jars/
ADD target/netty-handler-4.1.8.Final.jar /opt/apache/beam/jars/
ADD target/netty-handler-proxy-4.1.8.Final.jar /opt/apache/beam/jars/
ADD target/netty-resolver-4.1.8.Final.jar /opt/apache/beam/jars/
ADD target/netty-transport-4.1.8.Final.jar /opt/apache/beam/jars/
ADD target/netty-transport-native-epoll-4.1.8.Final.jar /opt/apache/beam/jars/
ADD target/objenesis-2.1.jar /opt/apache/beam/jars/
ADD target/org.apache.sling.commons.json-2.0.6.jar /opt/apache/beam/jars/
ADD target/paranamer-2.7.jar /opt/apache/beam/jars/
ADD target/pipeline-2.4.0-SNAPSHOT-shaded.jar /opt/apache/beam/jars/
ADD target/protobuf-java-3.2.0.jar /opt/apache/beam/jars/
ADD target/protobuf-java-util-3.2.0.jar /opt/apache/beam/jars/
ADD target/reactive-streams-1.0.0.jar /opt/apache/beam/jars/
ADD target/scala-java8-compat_2.11-0.7.0.jar /opt/apache/beam/jars/
ADD target/scala-library-2.11.11.jar /opt/apache/beam/jars/
ADD target/scala-parser-combinators_2.11-1.0.4.jar /opt/apache/beam/jars/
ADD target/scopt_2.11-3.5.0.jar /opt/apache/beam/jars/
ADD target/slf4j-api-1.7.25.jar /opt/apache/beam/jars/
ADD target/slf4j-jdk14-1.7.25.jar /opt/apache/beam/jars/
ADD target/snakeyaml-1.17.jar /opt/apache/beam/jars/
ADD target/snappy-java-1.1.4.jar /opt/apache/beam/jars/
ADD target/ssl-config-core_2.11-0.2.1.jar /opt/apache/beam/jars/
ADD target/xz-1.5.jar /opt/apache/beam/jars/

ADD target/linux_amd64/boot /opt/apache/beam/

ENTRYPOINT ["/opt/apache/beam/boot"]
